"""Updated user model

Revision ID: 29f649a23c28
Revises: daf63710b42d
Create Date: 2022-06-10 10:44:57.742790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f649a23c28'
down_revision = 'daf63710b42d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
