"""Added community model

Revision ID: 5e1c6de97546
Revises: 29f649a23c28
Create Date: 2022-06-10 11:53:55.041449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1c6de97546'
down_revision = '29f649a23c28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communitymembers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communitymembers_email'), 'communitymembers', ['email'], unique=True)
    op.create_index(op.f('ix_communitymembers_id'), 'communitymembers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communitymembers_id'), table_name='communitymembers')
    op.drop_index(op.f('ix_communitymembers_email'), table_name='communitymembers')
    op.drop_table('communitymembers')
    # ### end Alembic commands ###
